=== dini-ag-kim/hs-oer-lom-profil/draft/schemas/hs-oer-lom.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Diese XML Shema Description beschreibt ein auf LOM basierendes Metadatenformat, welches
beim Austausch von Metadaten zwischen OER Hochschulrepositorien in Deutschland
verwendet werden soll. Eine Dokumentation des Schemas findet sich unter
https://w3id.org/dini/hs-oer-lom-profil/ -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified"
  targetNamespace="https://www.oerbw.de/hsoerlom" 
  xmlns="https://www.oerbw.de/hsoerlom">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="https://w3id.org/kim/hs-oer-lom-profil/draft/schemas/xml.xsd"/>
  <xs:simpleType name="LOCISURI">
    <xs:restriction base="xs:string">
      <xs:enumeration value="URI"/>
      <xs:enumeration value="TEXT"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ATTRLANGNONE">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="LOM1SOURCE">
    <xs:sequence>
      <xs:element name="langstring" type="ATTRLANGNONE" fixed="LOMv1.0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CCCMSOURCE">
    <xs:sequence>
      <xs:element name="langstring" type="ATTRLANGNONE" fixed="https://w3id.org/kim/hcrt/scheme"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LANGSTRINGS">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute ref="xml:lang"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="DESCRIPTIONS">
    <xs:sequence>
      <xs:element name="langstring" type="LANGSTRINGS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="CATALOGS">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DOI"/>
      <xs:enumeration value="HDL"/>
      <xs:enumeration value="URN"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="AGGREGATLEVELVALUELIST">
    <xs:restriction base="xs:positiveInteger">
      <xs:maxInclusive value="4"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="AGGREGATLEVELVALUE">
    <xs:simpleContent>
      <xs:extension base="AGGREGATLEVELVALUELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="AGGREGATLEVEL">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="AGGREGATLEVELVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="STATUSVALUELIST">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Draft"/>
      <xs:enumeration value="Final"/>
      <xs:enumeration value="Revised"/>
      <xs:enumeration value="Unavailable"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="STATUSVALUE">
    <xs:simpleContent>
      <xs:extension base="STATUSVALUELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="STATUSTYPE">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="STATUSVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="CONTENTCONTRIBUTERROLELIST">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Author"/>
      <xs:enumeration value="Publisher"/>
      <xs:enumeration value="Unknown"/>
      <xs:enumeration value="Initiator"/>
      <xs:enumeration value="Terminator"/>
      <xs:enumeration value="Validator"/>
      <xs:enumeration value="Editor"/>
      <xs:enumeration value="Graphical Designer"/>
      <xs:enumeration value="Technical Implementer"/>
      <xs:enumeration value="Content Provider"/>
      <xs:enumeration value="Technical Validator"/>
      <xs:enumeration value="Educational Validator"/>
      <xs:enumeration value="Script Writer"/>
      <xs:enumeration value="Instructional Designer"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="CONTENTCONTRIBUTERROLEVALUE">
    <xs:simpleContent>
      <xs:extension base="CONTENTCONTRIBUTERROLELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="CONTENTCONTRIBUTORROLE">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="CONTENTCONTRIBUTERROLEVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="METACONTRIBUTORROLELIST">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Creator"/>
      <xs:enumeration value="Provider"/>
      <xs:enumeration value="Validator"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="METACONTRIBUTERROLEVALUE">
    <xs:simpleContent>
      <xs:extension base="METACONTRIBUTORROLELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="METACONTRIBUTORROLE">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="METACONTRIBUTERROLEVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DATES">
    <xs:sequence>
      <xs:element name="datetime" type="xs:date"/>
      <xs:element minOccurs="0" name="description" type="DESCRIPTIONS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TIMES">
    <xs:sequence>
      <xs:element name="datetime" type="xs:time"/>
      <xs:element minOccurs="0" name="description" type="DESCRIPTIONS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="LRT">
    <xs:sequence>
      <xs:element name="source" type="CCCMSOURCE"/>
      <xs:element name="id" type="LRTIDS"/>
      <xs:element minOccurs="0" ref="entry"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="LRTIDS">
    <xs:restriction base="xs:string">
      <xs:pattern value="https://w3id.org/kim/hcrt/([A-Za-z0-9_-])+"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="RIGHTSVALUELIST">
    <xs:restriction base="xs:string">
      <xs:enumeration value="yes"/>
      <xs:enumeration value="no"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="RIGHTSVALUE">
    <xs:simpleContent>
      <xs:extension base="RIGHTSVALUELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="RIGHTS">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="RIGHTSVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FACHCLASSPURPOSE">
    <xs:sequence>
      <xs:element name="source" type="LOM1SOURCE"/>
      <xs:element name="value">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="ATTRLANGNONE" fixed="Discipline"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TAXONS">
    <xs:sequence>
      <xs:element name="id" type="IDS"/>
      <xs:element minOccurs="0" ref="entry"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="IDS">
    <xs:restriction base="xs:string">
      <xs:pattern value="http://w3id.org/kim/hochschulfaechersystematik/[a-z]([0-9])+|[0-9][0-9][0-9]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HSFAECHERVALUELIST">
    <xs:restriction base="xs:string">
      <xs:enumeration value="https://w3id.org/kim/hochschulfaechersystematik/scheme"/>
      <xs:enumeration value="DDC"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="HSFAECHERVALUE">
    <xs:simpleContent>
      <xs:extension base="HSFAECHERVALUELIST">
        <xs:attribute ref="xml:lang" use="required" fixed="x-none"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="HSFAECHER">
    <xs:sequence>
      <xs:element name="source">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="langstring" type="HSFAECHERVALUE"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element maxOccurs="unbounded" name="taxon" type="TAXONS"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="entry">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="langstring" type="LANGSTRINGS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="metadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="lom"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lom">
    <xs:complexType>
      <xs:all>
        <xs:element ref="general"/>
        <xs:element ref="lifecycle"/>
        <xs:element minOccurs="0" ref="metametadata"/>
        <xs:element minOccurs="0" ref="technical"/>
        <xs:element minOccurs="0" ref="educational"/>
        <xs:element ref="rights"/>
        <xs:element minOccurs="0" ref="classification"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="general">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="identifier"/>
        <xs:element maxOccurs="unbounded" ref="title"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="catalogentry"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="language"/>
        <xs:element minOccurs="0" name="description" type="DESCRIPTIONS"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="keyword"/>
        <xs:element minOccurs="0" name="aggregationlevel" type="AGGREGATLEVEL"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="identifier" type="xs:string"/>
  <xs:element name="title">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="langstring" type="LANGSTRINGS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="catalogentry">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="catalog"/>
        <xs:element ref="entry"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="catalog" type="CATALOGS"/>
  <xs:element name="language">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:pattern value="[a-z][a-z]"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="keyword">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="langstring" type="LANGSTRINGS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="lifecycle">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="version"/>
        <xs:element minOccurs="0" name="status" type="STATUSTYPE"/>
        <xs:element maxOccurs="14" name="contribute">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="role" type="CONTENTCONTRIBUTORROLE"/>
              <xs:element maxOccurs="unbounded" ref="centity"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="metametadata">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="3" name="contribute">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="role" type="METACONTRIBUTORROLE"/>
              <xs:element maxOccurs="unbounded" ref="centity"/>
              <xs:element minOccurs="0" name="date" type="DATES"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="version">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="langstring" type="LANGSTRINGS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="centity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="vcard"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Das VCard-Format wird hier nicht genau spezifiziert, auch eine
       XML-Repräsentation ist in Übereinstimmung mit der LOM-Spezifikation
       nicht vorgesehen. Der Empfänger muss den Text entsprechend der Beispiele
       parsen können. -->
  <xs:element name="vcard" type="xs:string"/>
  <xs:element name="technical">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="format" type="xs:string"/>
        <xs:element minOccurs="0" name="size" type="xs:positiveInteger"/>
        <xs:element minOccurs="0" ref="location"/>
        <xs:element minOccurs="0" name="otherplatformrequirements" type="xs:string"/>
        <xs:element minOccurs="0" name="duration" type="TIMES"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="location">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="type" use="required" type="LOCISURI"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="educational">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="learningResourceType" type="LRT"/>
        <xs:element minOccurs="0" name="description" type="DESCRIPTIONS"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="rights">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="copyrightandotherrestrictions" type="RIGHTS"/>
        <xs:element name="description" type="DESCRIPTIONS">
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="classification">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="purpose" type="FACHCLASSPURPOSE"/>
        <xs:element maxOccurs="unbounded" name="taxonpath" type="HSFAECHER"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dini-ag-kim/hs-oer-lom-profil/draft/examples/full-example-a.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<metadata xmlns="https://www.oerbw.de/hsoerlom" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.oerbw.de/hsoerlom https://w3id.org/dini-ag-kim/hs-oer-lom-profil/draft/schemas/hs-oer-lom.xsd">
	<lom>
		<general>
			<identifier>c0a478bd-b5f0-4d67-89c5-4a49dfefddcf</identifier>
			<title>
				<langstring>Introduction to Difference Equations</langstring>
			</title>
			<catalogentry>
				<catalog>DOI</catalog>
				<entry>
					<langstring>10.1137/S0036144500378302</langstring>
				</entry>
			</catalogentry>
			<catalogentry>
				<catalog>HDL</catalog>
				<entry>
					<langstring>10900.3/OER_ZZxWvFJV</langstring>
				</entry>
			</catalogentry>
			<language>en</language>
			<description>
				<langstring>Vorbereitung auf einen Kurs zur Zeitreihenanalyse</langstring>
			</description>
			<keyword>
				<langstring xml:lang="de">Differenzengleichung</langstring>
			</keyword>
			<keyword>
				<langstring xml:lang="en">Difference Equation</langstring>
			</keyword>
		</general>
		<lifecycle>
			<version>
				<langstring>1.7</langstring>
			</version>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Author</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Dimpfl;Thomas
						FN:Thomas Dimpfl
						URL:https://orcid.org/0000-0003-3415-7412
						END:VCARD
					</vcard>
				</centity>
			</contribute>
		</lifecycle>
		<metametadata>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Creator</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Dimpfl;Thomas
						FN:Thomas Dimpfl
						URL:https://orcid.org/0000-0003-3415-7412
						END:VCARD
					</vcard>
				</centity>
				<date>
					<datetime>2019-02-11</datetime>
					<description>
						<langstring>Modified</langstring>
					</description>
				</date>
			</contribute>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Provider</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						ORG:Universität Tübingen
						URL:https://www.wikidata.org/entity/Q153978
						END:VCARD
					</vcard>
				</centity>
			</contribute>
		</metametadata>
		<technical>
			<format>video/mp4</format>
			<size>45061194</size>
			<location type="URI">https://www.oerbw.de/edu-sharing/components/render/c0a478bd-b5f0-4d67-89c5-4a49dfefddcf/1.7</location>
			<otherplatformrequirements>Es wird ein Videoplayer für MP4 benötigt.</otherplatformrequirements>
			<duration>
				<datetime>00:31:33</datetime>
				<description>
					<langstring>Playing time</langstring>
				</description>
			</duration>
		</technical>
		<educational>
			<learningResourceType>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hcrt/scheme</langstring>
				</source>
				<id>https://w3id.org/kim/hcrt/video</id>
				<entry>
					<langstring xml:lang="de">Video</langstring>
				</entry>
			</learningResourceType>
			<learningResourceType>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hcrt/scheme</langstring>
				</source>
				<id>https://w3id.org/kim/hcrt/course</id>
				<entry>
					<langstring xml:lang="de">Lernkurs</langstring>
				</entry>
			</learningResourceType>
		</educational>
		<rights>
			<copyrightandotherrestrictions>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">no</langstring>
				</value>
			</copyrightandotherrestrictions>
			<description>
				<langstring xml:lang="x-t-cc-url">
					https://creativecommons.org/publicdomain/zero/1.0/legalcode
				</langstring>
			</description>
		</rights>
		<classification>
			<purpose>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">Discipline</langstring>
				</value>
			</purpose>
			<taxonpath>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hochschulfaechersystematik/scheme</langstring>
				</source>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n4</id>
					<entry>
						<langstring>Mathematik, Naturwissenschaften</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n37</id>
					<entry>
						<langstring>Studienbereich Mathematik</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n276</id>
					<entry>
						<langstring>Wirtschaftsmathematik</langstring>
					</entry>
				</taxon>
			</taxonpath>
			<taxonpath>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hochschulfaechersystematik/scheme</langstring>
				</source>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n3</id>
					<entry>
						<langstring> Rechts-, Wirtschafts- und Sozialwissenschaften</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n30</id>
					<entry>
						<langstring>Wirtschaftswissenschaften</langstring>
					</entry>
				</taxon>
			</taxonpath>
		</classification>
	</lom>
</metadata>

=== dini-ag-kim/hs-oer-lom-profil/20200228/examples/full-example-b.xml
<?xml version = "1.0" encoding = "UTF-8" ?>
<metadata xmlns="https://www.oerbw.de/hsoerlom" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://www.oerbw.de/hsoerlom https://w3id.org/kim/hs-oer-lom-profil/20200228/schemas/hs-oer-lom.xsd">
	<lom>
		<general>
			<identifier>8dee40f6-0b22-4e5c-9d39-7ebeb7d20b9f</identifier>
			<title>
				<langstring>Baustein 5 Classroom Action Research</langstring>
			</title>
			<catalogentry>
				<catalog>HDL</catalog>
				<entry>
					<langstring>10900.3/OER_qiYOaTBN</langstring>
				</entry>
			</catalogentry>
			<language>de</language>
			<description>
				<langstring>Studierende führen im Rahmen von Praxisphasen Klassenforschungsprojekte durch.</langstring>
			</description>
			<keyword>
				<langstring>Aktionsforschung</langstring>
			</keyword>
			<keyword>
				<langstring>forschungsorientierte Lehre</langstring>
			</keyword>
			<keyword>
				<langstring>Unterrichtsforschung</langstring>
			</keyword>
			<aggregationlevel>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">2</langstring>
				</value>
			</aggregationlevel>
		</general>
		<lifecycle>
			<version>
				<langstring>1.6</langstring>
			</version>
			<status>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">Final</langstring>
				</value>
			</status>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Author</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Kolb;Annika
						FN: Annika Kolb
						END:VCARD
					</vcard>
				</centity>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Vonrhein;Ingrid
						FN:Ingrid Vonrhein
						END:VCARD
					</vcard>
				</centity>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Schocker;Marita
						FN:Marita Schocker
						END:VCARD
					</vcard>
				</centity>
			</contribute>
		</lifecycle>
		<metametadata>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Creator</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Faißt;Julia
						FN:Julia Faißt
						END:VCARD
					</vcard>
				</centity>
				<date>
					<datetime>2019-07-13</datetime>
					<description>
						<langstring>Modified</langstring>
					</description>
				</date>
			</contribute>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Validator</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						N:Schreiber;Anja
						FN:Anja Schreiber
						END:VCARD
					</vcard>
				</centity>
				<date>
					<datetime>2019-07-17</datetime>
					<description>
						<langstring>Published</langstring>
					</description>
				</date>
			</contribute>
			<contribute>
				<role>
					<source>
						<langstring xml:lang="x-none">LOMv1.0</langstring>
					</source>
					<value>
						<langstring xml:lang="x-none">Provider</langstring>
					</value>
				</role>
				<centity>
					<vcard>
						BEGIN:VCARD
						VERSION:3.0
						ORG:PH Freiburg
						URL:https://www.wikidata.org/entity/Q1441203
						END:VCARD
					</vcard>
				</centity>
			</contribute>
		</metametadata>
		<technical>
			<format>application/pdf</format>
			<size>873974</size>
		</technical>
		<educational>
			<learningResourceType>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hcrt/scheme</langstring>
				</source>
				<id>https://w3id.org/kim/hcrt/lesson_plan</id>
				<entry>
					<langstring xml:lang="de">Unterrichtsplanung</langstring>
				</entry>
			</learningResourceType>
			<description>
				<langstring>
					Die Studierenden lernen, wie Fragen der aktuellen Forschung in die Lehre integriert werden können.
				</langstring>
			</description>
		</educational>
		<rights>
			<copyrightandotherrestrictions>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">yes</langstring>
				</value>
			</copyrightandotherrestrictions>
			<description>
				<langstring xml:lang="x-t-cc-url">
					https://creativecommons.org/licenses/by-sa/4.0
				</langstring>
			</description>
		</rights>
		<classification>
			<purpose>
				<source>
					<langstring xml:lang="x-none">LOMv1.0</langstring>
				</source>
				<value>
					<langstring xml:lang="x-none">Discipline</langstring>
				</value>
			</purpose>
			<taxonpath>
				<source>
					<langstring xml:lang="x-none">https://w3id.org/kim/hochschulfaechersystematik/scheme</langstring>
				</source>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n3</id>
					<entry>
						<langstring> Rechts-, Wirtschafts- und Sozialwissenschaften</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n33</id>
					<entry>
						<langstring>Erziehungswissenschaften</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>http://w3id.org/kim/hochschulfaechersystematik/n052</id>
					<entry>
						<langstring>Erziehungswissenschaft (Pädagogik)</langstring>
					</entry>
				</taxon>
			</taxonpath>
			<taxonpath>
				<source>
					<langstring xml:lang="x-none">DDC</langstring>
				</source>
				<taxon>
					<id>300</id>
					<entry>
						<langstring>Social sciences</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>370</id>
					<entry>
						<langstring>Education</langstring>
					</entry>
				</taxon>
				<taxon>
					<id>378</id>
					<entry>
						<langstring>Higher education</langstring>
					</entry>
				</taxon>
			</taxonpath>
		</classification>
	</lom>
</metadata>
